name: deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: willfell/wac.lab.actions/.github/workflows/nextjs-site-deploy.yml@v1.12.2
    with:
      runner: will-fell
      role_arn: ${{ vars.AWS_ROLE_ARN }}
      aws_region: ${{ vars.AWS_REGION }}
      postbuild_command: yarn copy-resume
      invalidation_paths: /*.html /index.html /_next/* /*.pdf
    secrets:
      s3_bucket: ${{ secrets.S3_BUCKET_NAME }}
      cloudfront_distribution_id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
