name: Validate Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  validate-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
        working-directory: app

      - name: Validate Next.js Build
        run: yarn build
        working-directory: app
