name: pr

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-build:
    uses: willfell/lab.actions/.github/workflows/nextjs-site-check.yml@v1.6.0
  lint:
    uses: willfell/lab.actions/.github/workflows/actionlint.yml@v1.6.0
    permissions:
      contents: read
