name: pr

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-build:
    uses: willfell/wac.lab.actions/.github/workflows/nextjs-site-check.yml@v1.12.2
    with:
      runner: will-fell
  lint:
    uses: willfell/wac.lab.actions/.github/workflows/actionlint.yml@v1.12.2
    with:
      runner: will-fell
    permissions:
      contents: read
